# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Pipeline Name
name: $(Date:yyyy.MM.dd)-Parmeet-Service

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
# 1st Variable Group
- group: Mrutunjay
- name: my-passed-variable
  value: $[variables.Demo]
# 2nd Variable Group
- group: Mrutunjay
- name: my-passed-variable
  value: $[variables.Demo]

- name: SERVICE_NAME
  value: Parmeet-Service

stages:
- stage: Stage_1
  jobs:
  - job: Print_Stage_1_Variable_Name
    steps:
    - bash: echo $(my-passed-variable)

  - job: Get_BuildID
    steps:
    - bash: echo $(Build.BuildNumber)

- stage: Stage_2
  jobs:
  - job: Print_Stage_2_Variable_Name
    steps:
    - bash: echo $(my-passed-variable)

